In [2]:
# for loading, manipulating and cleaning the imported dataset
import pandas as pd
# for fast mathematical operations and handling numerical missing values
import numpy as np
# matplotlib's plotting tool to create basic visualisations like charts, lines, and figures
import matplotlib.pyplot as plt
# (built on top of matplotlib) to create prettier, advanced statistical graphs like boxplots
import seaborn as sns

In [3]:
# Loads the messy CSV file into a pandas DataFrame (a table structure called 'df') for analysis
# pd.read_csv(): The function from the pandas library used to read CSV files.
df = pd.read_csv("crime_incidents_messy.csv")

In [4]:
# display 1st 5 rows of dataset
df.head()

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
0,INC001115,asslt,Sou,Maplewood,GA,2830 Cedar Lane,170.284100,-77.500710,2024-04-16 08:45:03,OFF0078,...,Unknown,6223265920,Firearm,2,Open,No Arrest,NaN,NaN,True,Incident at 2830 Cedar Lane. Officer responded...
1,INC004706,burglary,southeast,Maplewood,OH,2361 Park Rd,29.422717,-77.167016,2022-01-11 22:03:29,OFF0059,...,NaN,241-973-4826,Firearm,3,NaN,NaN,2.0,44839.49,yes,Incident at 2361 Park Rd. Officer responded at...
2,INC002249,Homocide,Southwest,Lakewood,AZ,1067 Main St,39.411460,-98.615298,2022-04-14 11:39:24,OFF0088,...,Other,244-584-7696,KNIFE,1,CLOSED,warning,2.0,15963.38,YES,Incident at 1067 Main St. Officer responded at...
3,INC000021,Property Damage,Cen,Springfield,AZ,4713 Washington Ave,28.633439,-99.030051,2020-12-09 15:14:24,OFF0077,...,NaN,5021227484,hands,Low,Resolved,NaN,5.0,48680.14,False,Incident at 4713 Washington Ave. Officer respo...
4,INC000488,Domestc Violence,North,Lakewood,PA,1371 River Rd,34.217850,-121.614731,2021-07-24 20:08:13,OFF0083,...,M,9698766873,Unarmed,MEDIUM,Closed,Warning Issued,2.0,23513.01,YES,NaN

In [5]:
# df.shape is to display numbers of columns and rows
print(f"dataset shaper:{df.shape}\n")

dataset shaper:(5250, 33)

In [6]:
# Prints a summary of the DataFrame, including total rows, column names, non-null counts, and data types (dtypes)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5250 entries, 0 to 5249
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5250 non-null   object
 1   crime_type          5250 non-null   object
 2   district            5250 non-null   object
 3   city                5250 non-null   object
 4   state               5250 non-null   object
 5   address             5250 non-null   object
 6   latitude            4992 non-null   float64
 7   longitude           4961 non-null   float64
 8   incident_datetime   4910 non-null   object
 9   officer_id          5250 non-null   object
 10  officer_first_name  5250 non-null   object
 11  officer_last_name   5250 non-null   object
 12  badge_number        4938 non-null   float64
 13  suspect_id          4440 non-null   object
 14  suspect_first_name  4440 non-null   object
 15  suspect_last_name   4440 non-null   object
 16  suspect_age         4153 non-null   float64
 17  suspect_gender      3837 non-null   object
 18  suspect_race        3649 non-null   object
 19  victim_id           4993 non-null   object
 20  victim_first_name   4993 non-null   object
 21  victim_last_name    4993 non-null   object
 22  victim_age          4688 non-null   float64
 23  victim_gender       4250 non-null   object
 24  victim_phone        4194 non-null   object
 25  weapon_used         4280 non-null   object
 26  severity            4895 non-null   object
 27  case_status         4519 non-null   object
 28  resolution          4299 non-null   object
 29  num_arrests         4917 non-null   float64
 30  property_loss_usd   4814 non-null   object
 31  reported_online     4746 non-null   object
 32  notes               4181 non-null   object
dtypes: float64(6), object(27)
memory usage: 1.3+ MB

In [7]:
# Generates summary statistics for ALL columns (numerical and text) to reveal averages, ranges, unique values, and frequent categories
df.describe(include = 'all')

,incident_id,crime_type,district,city,state,address,latitude,longitude,incident_datetime,officer_id,...,victim_gender,victim_phone,weapon_used,severity,case_status,resolution,num_arrests,property_loss_usd,reported_online,notes
count,5250,5250,5250,5250,5250,5250,4992.000000,4961.000000,4910,5250,...,4250,4194,4280,4895,4519,4299,4917.000000,4814,4746,4181
unique,5050,182,131,8,10,4895,NaN,NaN,4675,150,...,12,3994,13,14,12,9,NaN,4592,10,3915
top,INC002391,Fire Setting,Nor,Riverside,FL,9657 Park Rd,NaN,NaN,2021-01-18 03:05:30,OFF0015,...,Male,648-499-1968,Hands/Feet,4,closed,Arrest Made,NaN,20611.06,0,Incident at 8687 Maple Dr. Officer responded a...
freq,2,84,273,740,554,3,NaN,NaN,3,53,...,394,3,368,376,399,504,NaN,3,539,3
mean,NaN,NaN,NaN,NaN,NaN,NaN,40.778811,-88.607610,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.262152,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,23.243225,37.214207,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.994556,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,25.002420,-121.975849,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-5.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,30.966472,-108.040512,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,36.967123,-94.656440,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,43.051502,-80.588056,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,199.984200,99.787300,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN

In [8]:
# Counts how many total rows in the DataFrame are exact duplicates of another row
# .sum(): Adds up all the True values (since Python treats True as 1), giving you the exact total count of duplicate rows.
duplicate_count = df.duplicated().sum()

print(f"number of duplicated rows: {duplicate_count}")

number of duplicated rows: 200

In [9]:
# Removes exact duplicate rows (keeping the very first one) and resets the row index so there are no missing numbers
df = df.drop_duplicates(keep = 'first').reset_index(drop=True)

In [10]:
# Clean column names: strip edge whitespace, convert to lowercase, and replace spaces with underscores
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_')

In [11]:
# Prints a summary of the DataFrame, including total rows, column names, non-null counts, and data types (dtypes)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   object
 1   crime_type          5050 non-null   object
 2   district            5050 non-null   object
 3   city                5050 non-null   object
 4   state               5050 non-null   object
 5   address             5050 non-null   object
 6   latitude            4799 non-null   float64
 7   longitude           4772 non-null   float64
 8   incident_datetime   4721 non-null   object
 9   officer_id          5050 non-null   object
 10  officer_first_name  5050 non-null   object
 11  officer_last_name   5050 non-null   object
 12  badge_number        4749 non-null   float64
 13  suspect_id          4275 non-null   object
 14  suspect_first_name  4275 non-null   object
 15  suspect_last_name   4275 non-null   object
 16  suspect_age         3998 non-null   float64
 17  suspect_gender      3698 non-null   object
 18  suspect_race        3525 non-null   object
 19  victim_id           4802 non-null   object
 20  victim_first_name   4802 non-null   object
 21  victim_last_name    4802 non-null   object
 22  victim_age          4508 non-null   float64
 23  victim_gender       4087 non-null   object
 24  victim_phone        4031 non-null   object
 25  weapon_used         4120 non-null   object
 26  severity            4708 non-null   object
 27  case_status         4354 non-null   object
 28  resolution          4138 non-null   object
 29  num_arrests         4726 non-null   float64
 30  property_loss_usd   4636 non-null   object
 31  reported_online     4564 non-null   object
 32  notes               4022 non-null   object
dtypes: float64(6), object(27)
memory usage: 1.3+ MB

In [12]:
# Strip trailing/leading spaces and convert all text in 'crime_type' to lowercase
df['crime_type'] = df['crime_type'].str.strip().str.lower()
# Strip trailing/leading spaces and convert all text in 'case_status' to lowercase
df['case_status'] = df['case_status'].str.strip().str.lower()
# Print an array of all distinct crime categories to check for typos and duplicates
print(df['crime_type'].unique())

['asslt' 'burglary' 'homocide' 'property damage' 'domestc violence'
 'breaking & entering' 'robbery' 'manslaughter' 'b&e' 'narcotics'
 'burglry' 'theft' 'fraudulent activity' 'drug offense' 'armed robbery'
 'arsen' 'abduction' 'graffiti' 'trespass' 'cyber crime' 'trespassing'
 'sexual assault' 'fraud' 'theft/larceny' 'larceny' 'arson' 'homicide'
 'tresspassing' 'cybercrime' 'hacking' 'assault' 'sexual assualt'
 'fire setting' 'drug offence' 'drunk driving' 'duii' 'robbry' 'vandalism'
 'vandlism' 'murder' 'kidnaping' 'kidnapping' 'd.u.i.' 'roberry'
 'assault & battery' 'dv' 'domestic violence' 'scam' 'sex assault'
 'dom. violence' 'sa' 'deception' 'battery' 'dwi' 'dui' 'drugs'
 'online fraud' 'stealing' 'assault  &  battery' 'sexual  assualt'
 'sexual  assault' 'drug  offense' 'sex  assault' 'armed  robbery'
 'domestic  violence' 'property  damage' 'drug  offence' 'cyber  crime']

In [13]:
# 1. First, squash multiple internal spaces down to single spaces and strip edges
df['crime_type'] = df['crime_type'].str.replace(r'\s+', ' ', regex=True).str.strip()
# 2. Clean dictionary (no trailing spaces, correct targets)
typo_map = {
    'asslt': 'assault', 
    'homocide': 'homicide', 
    'murder': 'homicide',
    'domestc violence': 'domestic violence', 
    'dv': 'domestic violence', 
    'dom. violence': 'domestic violence',
    'b&e': 'breaking & entering', 
    'narcotics': 'drug offense', 
    'drug offence': 'drug offense', 
    'drugs': 'drug offense',
    'burglry': 'burglary', 
    'fraudulent activity': 'fraud', 
    'scam': 'fraud', 
    'deception': 'fraud', 
    'online fraud': 'fraud',
    'arsen': 'arson', 
    'fire setting': 'arson',
    'trespass': 'trespassing', 
    'tresspassing': 'trespassing',
    'cyber crime': 'cybercrime', 
    'sexual assualt': 'sexual assault', 
    'sex assault': 'sexual assault',
    'sa': 'sexual assault',
    'drunk driving': 'dui', 
    'duii': 'dui', 
    'd.u.i': 'dui', 
    'dwi': 'dui', 
    'd.u.i.': 'dui',
    'robbry': 'robbery', 
    'roberry': 'robbery',
    'vandlism': 'vandalism', 
    'kidnaping': 'kidnapping', 
    'stealing': 'theft'
}
# 3. Apply replacement once
df['crime_type'] = df['crime_type'].replace(typo_map)

In [14]:
# Prints the list of all unique crime categories remaining in the 'crime_type' column to verify that typos have been successfully cleaned
print(df['crime_type'].unique())

['assault' 'burglary' 'homicide' 'property damage' 'domestic violence'
 'breaking & entering' 'robbery' 'manslaughter' 'drug offense' 'theft'
 'fraud' 'armed robbery' 'arson' 'abduction' 'graffiti' 'trespassing'
 'cybercrime' 'sexual assault' 'theft/larceny' 'larceny' 'hacking' 'dui'
 'vandalism' 'kidnapping' 'assault & battery' 'battery']

In [15]:
# Prints a summary of the DataFrame, including total rows, column names, non-null counts, and data types (dtypes)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5050 entries, 0 to 5049
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   incident_id         5050 non-null   object
 1   crime_type          5050 non-null   object
 2   district            5050 non-null   object
 3   city                5050 non-null   object
 4   state               5050 non-null   object
 5   address             5050 non-null   object
 6   latitude            4799 non-null   float64
 7   longitude           4772 non-null   float64
 8   incident_datetime   4721 non-null   object
 9   officer_id          5050 non-null   object
 10  officer_first_name  5050 non-null   object
 11  officer_last_name   5050 non-null   object
 12  badge_number        4749 non-null   float64
 13  suspect_id          4275 non-null   object
 14  suspect_first_name  4275 non-null   object
 15  suspect_last_name   4275 non-null   object
 16  suspect_age         3998 non-null   float64
 17  suspect_gender      3698 non-null   object
 18  suspect_race        3525 non-null   object
 19  victim_id           4802 non-null   object
 20  victim_first_name   4802 non-null   object
 21  victim_last_name    4802 non-null   object
 22  victim_age          4508 non-null   float64
 23  victim_gender       4087 non-null   object
 24  victim_phone        4031 non-null   object
 25  weapon_used         4120 non-null   object
 26  severity            4708 non-null   object
 27  case_status         4354 non-null   object
 28  resolution          4138 non-null   object
 29  num_arrests         4726 non-null   float64
 30  property_loss_usd   4636 non-null   object
 31  reported_online     4564 non-null   object
 32  notes               4022 non-null   object
dtypes: float64(6), object(27)
memory usage: 1.3+ MB

In [16]:
# Cleans the 'property_loss_usd' column by stripping out currency symbols ($), commas (,), and text, keeping ONLY numbers and decimal points
df['property_loss_usd'] = df['property_loss_usd'].astype(str).str.replace(r'[^\d]', '', regex=True)

In [17]:
# Converts the 'property_loss_usd' column to numeric floats, turning any unparseable values into NaN (missing data)
# pd.to_numeric(...): Pandas function that transforms string representations of numbers (like '1250.50') into actual numerical numbers (1250.50) so you can perform calculations, sums, and averages.
# errors='coerce': The safety switch. If pandas runs into a value it can't convert into a number (like 'unknown', 'N/A', or empty strings ''), instead of crashing your code with a ValueError, it safely converts that bad value into NaN (Not a Number / missing value).
df['property_loss_usd'] = pd.to_numeric(df['property_loss_usd'], errors='coerce')

In [18]:
# Print the data type of the 'property_loss_usd' column to verify it successfully converted to a float (numeric)
print("Column Type:", df['property_loss_usd'].dtype)
# Print a header for readability in the output
print("\nFirst 5 values after cleaning:")
# Display the first 5 rows of the cleaned numeric column to double-check the values
print(df['property_loss_usd'].head())

Column Type: float64

First 5 values after cleaning:
0          NaN
1    4483949.0
2    1596338.0
3    4868014.0
4    2351301.0
Name: property_loss_usd, dtype: float64

In [19]:
# Convert the 'incident_datetime' column into standardized pandas Datetime objects, handling mixed structures and turning invalid dates into NaT
df['incident_datetime'] = pd.to_datetime(df['incident_datetime'], errors='coerce', format='mixed')

# Print the first 5 entries to confirm the dates now use the standard YYYY-MM-DD HH:MM:SS layout
print(df['incident_datetime'].head())

0   2024-04-16 08:45:03
1   2022-01-11 22:03:29
2   2022-04-14 11:39:24
3   2020-12-09 15:14:24
4   2021-07-24 20:08:13
Name: incident_datetime, dtype: datetime64[ns]

Get the year: df['incident_datetime'].dt.year

Get the month: df['incident_datetime'].dt.month

Get the day of the week: df['incident_datetime'].dt.day_name()

In [20]:
# Fill missing values (NaN) in the 'victim_gender' column with the placeholder text 'unknown'
df['victim_gender'] = df['victim_gender'].fillna('unknown')

# Fill missing values (NaN) in the 'suspect_gender' column with the placeholder text 'unknown'
df['suspect_gender'] = df['suspect_gender'].fillna('unknown')

# Replace missing values (NaN) in 'victim_age' with the median age of all victims to prevent data distortion from extreme outliers
df['victim_age'] = df['victim_age'].fillna(df['victim_age'].median())

# Replace missing values (NaN) in 'suspect_age' with the median age of all suspects
df['suspect_age'] = df['suspect_age'].fillna(df['suspect_age'].median())

# Verify the changes by printing the count of missing (NaN) values remaining in these four specific columns
print(df[['victim_gender','suspect_gender', 'victim_age', 'suspect_age']].isna().sum())

victim_gender     0
suspect_gender    0
victim_age        0
suspect_age       0
dtype: int64